# Dependencies
markdown:         kramdown
highlighter:      rouge

collections:
  people:       { output: true, permalink: /lab/people/:name/ }
  projects:     { output: true, permalink: /lab/projects/:name/ }
  publications: { output: true, permalink: /lab/publications/:name/ }
  news:         { output: true, permalink: /lab/news/:name/ }

defaults:
  - scope: { path: "", type: "people" }       # People pages
    values: { layout: default }
  - scope: { path: "", type: "projects" }     # Projects
    values: { layout: default }
  - scope: { path: "", type: "publications" } # Publications
    values: { layout: default }
  - scope: { path: "", type: "news" }         # News posts
    values: { layout: default }

# Setup
title:            Soneya Hossain
tagline:          'Soneya Hossain'
description:      'Assistant Professor Computer Science University of Texas at Dallas'
url:              https://soneyahossain.github.io
#baseurl:          /

author:
  name:           'Soneya Hossain'
  #url:            https://soneyahossain.github.io

logo:             /assets/img/profile_.jpg
#paginate:         5
gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-gist, jekyll-include-cache]

plugins:
  - jekyll-paginate
  - jekyll-include-cache


# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/soneyahossain/soneyahossain.github.io/

tags:

email_username: 'sbhossain@utdallas.edu'
github_username:  soneyahossain
scholar_username: 'https://scholar.google.com/citations?user=xDDfwB8AAAAJ&hl=en'
linkedin_username: Soneya

